bidmanager/bidmanager/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import patterns, include, url
from django.conf import settings
from bids.views import ContactFormView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from bids.sitemaps import BidSitemap

sitemaps = {
    'bid': BidSitemap,
}

urlpatterns = patterns('',
                       url(r'^$', 'bids.views.home', name='home'),
                       url(r'^about$', 'bids.views.about', name='about'),
                       url(r'^contact$', ContactFormView.as_view(), name='contact'),
                       url(r'^email-sent/?$', 'bids.views.email_sent', name='email-sent'),
                       url(r'^how-to$', 'bids.views.howto', name='howto'),
                       url(r'^search$', 'bids.views.search', name='search'),
                       url(r'^search_status$', 'bids.views.search_status', name='search_status'),
                       url(r'^county/(?P<county_slug>[^\/]+)$', 'bids.views.county', name='county'),
                       url(r'^location/(?P<location>\d+)/.*$', 'bids.views.location', name='location'),
                       url(r'^[a-z|-]+/bid/(?P<bid_id>\d+)/?$', 'bids.views.bid_detail', name='bid_detail'),
                       url(r'^backend$', 'backend.views.dashboard', name='dashboard'),
                       url(r'^backend/edit/(?P<source_id>[^\/])$', 'backend.views.editcrawl', name='edit'),
                       (r'^profile/login/$', 'profiles.views.login_user'),
                       (r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
                       url(r'^admin/', include(admin.site.urls)),
                       )


if settings.DEBUG:
    urlpatterns += patterns('',
      (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes':True}),
    )


"""
Sitemap def

Ordered by frequency - how to provide xlinks from site?

/county/<county_slug>/bid-title(shortened)/id1
/county/<county_slug>/bid-title(shortened)/id2

/category/bid-title/id1



"""

bidmanager/bids/models.py
from datetime import datetime
from django.db import models
from django.contrib import admin
from django.conf import settings
from django.forms import TextInput, Textarea
from django.utils.timezone import utc
from django.utils.translation import ugettext as _
from model_utils import Choices
from model_utils.fields import StatusField
from model_utils.models import TimeStampedModel
from picklefield.fields import PickledObjectField


class State(TimeStampedModel):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)

    def __unicode__(self):
        return self.name

    class Meta:
        db_table = 'state'        


class FrontendSite(TimeStampedModel):
    name = models.CharField(max_length=100)
    url = models.CharField(max_length=50)
    state = models.ForeignKey('State')

    def __unicode__(self):
        return self.name

    class Meta:
        db_table = 'frontend'


class County(TimeStampedModel):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    state = models.ForeignKey('State')

    def __unicode__(self):
        return self.name

    class Meta:
        db_table = 'county'


    def get_absolute_url(self):
        return "/county/%s" % self.slug

    @staticmethod
    def choices():
        #return County.objects.all()
        return [(c.name, c.name) for c in County.objects.all()]


class BidCategory(TimeStampedModel):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)

    def __unicode__(self):
        return self.name

    class Meta:
        db_table = 'category'        

    @staticmethod
    def choices():
        #return BidCategory.objects.all()
        return [(c.slug, c.name) for c in BidCategory.objects.all()]        


class BidSource(TimeStampedModel):

    STATUS = Choices(
        ('new', _('New')),
        ('ok', _('Good')),
        ('review', _('Needs review')),        
        ('error', _('In Error')),
    )

    CRAWL_TYPE = Choices(
        ('notify', _('Notify')),
        ('import', _('Auto Import'))
    )

    LEVEL = Choices(
        ('county', _('County')),
        ('state', _('State')),
        ('federal', _('Federal')),
        ('muncipal', _('Municpal')),
    )

    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    url = models.CharField(max_length=1000)
    level = models.CharField(choices=LEVEL, max_length=20, default=LEVEL.county)    
    last_crawled = models.DateTimeField(null=True, blank=True)
    crawl_message = models.CharField(max_length=1000, null=True, blank=True)
    crawl_status = StatusField()
    # Type: Notify - email if content changed, Import - crawl+import job set up for this source
    crawl_type = models.CharField(choices=CRAWL_TYPE, default=CRAWL_TYPE.notify, max_length=20)
    # CSS selector target used to tell if content has changed, leave blank for full page body
    crawl_target = models.CharField(max_length=1000, null=True, blank=True)
    crawl_hash = models.CharField(max_length=1000, null=True, blank=True)
    enabled = models.BooleanField(default=True)
    # Default contact info for bids on this site
    contact_name = models.CharField(max_length=1000, null=True, blank=True)
    contact_phone = models.CharField(max_length=1000, null=True, blank=True)
    county = models.ForeignKey('County', null=True, blank=True)
    crawl_code = models.TextField(null=True, blank=True)

    objects = models.Manager()

    class Meta:
        db_table = 'source'    

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return "/location/%s/%s-%s-%s" % (self.id, self.county.state.slug, self.county.slug, self.slug)

    def done_crawl(self, success, message, hash):
        now = datetime.utcnow().replace(tzinfo=utc)
        self.last_crawled = now
        self.content_hash = hash
        self.save()


class BidSourceAdmin(admin.ModelAdmin):
    exclude = ('last_crawled','crawl_hash','crawl_message','crawl_status',)


class BidManager(models.Manager):
    def published(self):
        if settings.DEBUG:
            return self.get_query_set()
        else:
            return self.get_query_set().filter(status=Bid.STATUS.published)

class Bid(TimeStampedModel):

    STATUS = Choices(
        ('new', _('New')),
        ('published', _('Published')),
        ('closed', _('Closed')),
        ('ignore', _('Ignore')),        
    )

    orig_id = models.CharField(max_length=1000, null=True, blank=True, 
                                help_text="Unique ID from src sys",)
    status = StatusField(default=STATUS.new)
    source = models.ForeignKey('BidSource')
    category = models.ForeignKey('BidCategory', blank=True, null=True)
    title = models.CharField(max_length=1000, blank=True)
    description = models.TextField(blank=True, help_text=_("Use markdown syntax"))
    contact_name = models.CharField(max_length=1000, blank=True)
    contact_phone = models.CharField(max_length=1000, blank=True)
    open_date = models.DateTimeField(null=True, blank=True)
    end_date = models.DateTimeField(null=True, blank=True)
    content_hash = models.CharField(max_length=1000, blank=True)
    extra_info = PickledObjectField()
    view_count = models.IntegerField(default=0)
    url = models.CharField(max_length=1000)

    
    objects = BidManager()#models.Manager()

    class Meta:
        db_table = 'bid'

    def __unicode__(self):
        return "%s - %s - %s" % (self.source, self.title[:60], self.status)

    def get_absolute_url(self):
        return "/%s/bid/%s" % (self.source.county.slug, self.id)


class BidAdmin(admin.ModelAdmin):
    exclude = ('orig_id', 'content_hash',)
    readonly_fields = ('view_count', 'url', 'source', )
    formfield_overrides = {
        models.CharField: {'widget': TextInput(attrs={'size':'150'})},
        models.TextField: {'widget': Textarea(attrs={'rows':25, 'cols':120})},
    }



"""

class Attachment(TimeStampedModel):
    TYPE = Choices(
        ('spec', _('Spec')),
        ('results', _('Results')),
    )

    bid = models.ForeignKey('Bid')
    url = models.CharField(max_length=1000)
    kind = models.CharField(choices=TYPE, max_length=20)
"""

admin.site.register(FrontendSite)
admin.site.register(State)
admin.site.register(County)
admin.site.register(BidCategory)
admin.site.register(BidSource, BidSourceAdmin)
admin.site.register(Bid, BidAdmin)

bidmanager/bids/forms.py
#from django import forms
#from crispy_forms.helper import FormHelper
#from crispy_forms.layout import Submit
import floppyforms as forms
from .models import BidCategory, County


class SearchForm(forms.Form):
    counties = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, choices=County.choices())
    categories = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, choices=BidCategory.choices())


class ContactForm(forms.Form):

    name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        #self.helper = FormHelper()
        #self.helper.add_input(Submit('submit', 'Submit'))
        super(ContactForm, self).__init__(*args, **kwargs)

bidmanager/bids/views.py
import logging
from django.shortcuts import render, get_object_or_404
from django.core.mail import send_mail
from django.views.generic import FormView
from haystack.query import SearchQuerySet
from haystack.inputs import AutoQuery, Exact, Clean
from django.http import HttpResponse
from django.conf import settings
from .forms import SearchForm, ContactForm
from .models import *
from profiles.models import BidsUser

#from django.contrib.auth import get_user_model


def about(request):
    """About Us page"""
    #sources = BidSource.objects.filter(county__state__id=request.state_filter).order_by('county')
    counties = County.objects.select_related().filter(state__id=request.state_filter).order_by('name')
    return render(request, 'bids/about.html', {'counties': counties})


class ContactFormView(FormView):
    form_class = ContactForm
    template_name = "bids/contact_form.html"
    success_url = '/email-sent/'

    def form_valid(self, form):
        users = BidsUser.objects.filter(is_admin=True).values('email')
        mail_to = [u['email'] for u in users]
        message = "{name} / {email} said: ".format(
            name=form.cleaned_data.get('name'),
            email=form.cleaned_data.get('email'))
        message += "\n\n{0}".format(form.cleaned_data.get('message'))
        send_mail(
            subject="JerseyBids contact - %s " % form.cleaned_data.get('subject').strip(),
            message=message,
            from_email=settings.EMAIL_FROM,
            recipient_list=mail_to,
        )
        return super(ContactFormView, self).form_valid(form)

def email_sent(request):
    return render(request, 'bids/email_sent.html', {})


def county(request, county_slug):
    """County page"""
    county = get_object_or_404(County, slug=county_slug)
    bids = Bid.objects.published().filter(source__county=county)
    print "LSDLNF : %s" % len(bids)
    return render(request, 'bids/county.html', {'county':county, 'bids':bids})

def location(request, location):
    """Location page"""
    #ser = request.user if request.user.is_authenticated() else None
    location = get_object_or_404(BidSource, pk=location)
    bids = Bid.objects.published().filter(source=location)
    return render(request, 'bids/location.html', {'location':location, 'bids': bids})

def home(request):
    """Home page"""
    return render(request, 'bids/home.html', {})


def howto(request):
    """HowTo page"""
    return render(request, 'bids/howto.html', {})


def bid_detail(request, bid_id):
    prev_url = request.session.get('prev_url')
    bid = get_object_or_404(Bid, pk=bid_id)
    return render(request, 'bids/bid_detail.html', {'bid': bid, 'prev_url': prev_url})


def search(request):
    request.session['prev_url'] = request.build_absolute_uri()
    q = request.GET.get('q')
    levels = request.GET.get('levels')
    counties = request.GET.get('counties')
    categories = request.GET.get('categories')

    # Text query
    if q is None:
        results = SearchQuerySet().all()
    else:
        results = SearchQuerySet().filter(content=AutoQuery(q))

    # Add filters
    results = results.filter(state=request.state_filter)
    if levels:
        levels = levels.split('-')
        results = results.filter(level__in=levels)
    if categories:
        categories = categories.split('-')
        results = results.filter(category__in=categories)
    if counties:
        counties = counties.split('-')
        results = results.filter(county__in=counties)

    rtitle = "Showing %s results" % len(results)
    levels = ['state', 'county', 'municipal']
    return render(request, 'bids/search.html',
        {'result_title': rtitle, 'results': results, 'cats': BidCategory.choices(),
         'counties': County.choices(), 'levels': levels })


def search_status(request):
    all = SearchQuerySet().all()
    out = ""
    for a in all:
        s = str(a.get_stored_fields())
        out += "%s" % s.replace(",", "<br>")
        #for f in a.get_stored_fields():
        #    out += "%s %s<br>" % (f, f.value)
        out += "<br><br>"
    return HttpResponse("Total items: %s<br>" % len(all) + out)

bidmanager/templates/bids/_result.html
<tr class="clickable">
	<td>{{r.source.county}}</td>	
	<td>{{r.category}}</td>
	<td><a href="{{r.get_absolute_url}}">{{r.title}}</a></td>
	<td>{{r.date|date:"SHORT_DATE_FORMAT"}}</td>
</tr>

bidmanager/templates/bids/_search_result.html
<tr class="clickable">
	<td>{{r.county}}</td>	
	<td>{{r.category}}</td>
	<td><a href="{{r.object.source.slug}}/bid/{{r.object.id}}">{{r.title}}</a></td>
	<td>{{r.date|date:"SHORT_DATE_FORMAT"}}</td>
</tr>

bidmanager/templates/bids/about.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
	<div class="span12 facet">
		<h3>JerseyBids provides a single interface to find Bids across every county in NJ</h3>
		<span class="divider"></span>
		{% for c in counties %}
			<ul style="float:left;display:block:width:300px;list-style-type:none">
				<li><b><a href="{{c.get_absolute_url}}">{{c}}</a></b></li>
				{% for s in c.bidsource_set.all %}
				<li><a href="{{s.url}}">{{s.name}}</a></li>
				{% endfor %}
			</ul>
		{% endfor %}
	</div>
</div>
{% endblock %}

bidmanager/templates/bids/bid_detail.html
{% extends 'base.html' %}
{% load markup %}
{% block title %}{{bid.title}} - {{bid.catetory}} - {{bid.source.county}}.{% endblock %}
{% block metadesc %}{{bid.title}}.  {{bid.meta_description}}{% endblock %}
{% block metakey%}{{bid.source.county.state}},{{bid.source.county}},{{bid.source}},bids,rfps,proposals,goverment,municipal,{{bid.title}}{% endblock %}
{% block onready %}
{% endblock %}
{% block content %}


<div class="row">
	<div class="span10 offset1 bid">
		{% if prev_url %}
		<a href="{{prev_url}}">Back to results</a>
		{% endif %}

		<h1>{{bid.title}}</h1>
		<div class="row detail form-inline">
			<div class="span3 text-left">
				<b>Location</b>: <a href="{{bid.source.get_absolute_url}}">{{bid.source}}</a>
				<br>
				<b>County</b>: <a href="{{bid.source.county.get_absolute_url}}">{{bid.source.county}}</a>
				<br>
				<b>Category</b>: <a href="{{bid.category.get_absolute_url}}">{{bid.category}}</a>
			</div>
			<div class="span3 text-left">
				<b>Open Date</b>: {{bid.open_date|date}}
				<br/>
				<b>End Date</b>: {{bid.end_date|date}}
			</div>	
			<div class="span3 text-left">
				<b>Contact</b>: {{bid.contact_name}}
				<br/>
				<b>Phone</b>: {{bid.contact_phone}}
				<br>
				<b>Source</b>: <a href="{{bid.url}}" target="_newtab">View</a>
			</div>				
		</div>
		
		<div class="bid_description">
			{{bid.description|markdown:"safe"}}
		</div>

	</div>
</div>


{% endblock %}

bidmanager/templates/bids/contact.html
{% extends 'base.html' %}

{% block content %}
<div class="hero-unit">
    <h1>Welcome to Jersey Bids</h1>
    <br/>
    <p>We supply updates and knowledge on current and upcoming bids, RFPs, and government contracts to keep you, the contractor, continuously aware of new projects and their specifications</p>
    <p><a href="/search" class="btn btn-primary btn-large">Start Searching &raquo;</a></p>
</div>

{% endblock %}

bidmanager/templates/bids/contact_form.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block title %}Contact Us{% endblock %}
{% block onready %}$('#id_name').focus();{% endblock %}
{% block content %}
    <div class="row">
        <div class="span6 offset3">
            <h1>Send an email</h1>
            <form method="post" action="" class="contact">
            {{ form|bootstrap }}
            {% csrf_token %}
            <input type="submit" value="Submit"/>
        	</form>
        </div>
    </div>
{% endblock %}

bidmanager/templates/bids/county.html
{% extends 'base.html' %}
{% block title %}{{location}} Bids{% endblock %}
{% block onready %}	
{% endblock %}
{% block content %}

<div class="row">
	<div class="span8 offset1">

		<h2>{{county}} Bids</h2>
		<table class="table table-striped table-bordered table-condensed">
			<thead>
			<tr>
				<th width="15%">County</th>
				<th width="15%">Category</th>
				<th width="60%">Title</th>
				<th width="10%">Date</th>
			</tr>
			</thead>
			<tbody>
			{% for r in bids %}
				{% include 'bids/_result.html' %}
			{% endfor %}
			</tbody>
		</table>

	</div>
</div>


{% endblock %}

bidmanager/templates/bids/email_sent.html
{% extends 'base.html' %}
{% load markup %}
{% block title %}Message Sent!{% endblock %}
{% block content %}
<br>
<div class="row detail">
	<div class="span5 offset3 text-center">
		<h3>Message sent.  Thanks!</h3>
	</div>
</div>


{% endblock %}

bidmanager/templates/bids/home.html
{% extends 'base.html' %}

{% block content %}
<div class="hero-unit" style="padding-top:10px">
    <h2>Welcome to Jersey Bids</h2>
    <!--<p>We supply updates and knowledge on current and upcoming bids, RFPs, and government contracts to keep you, the contractor, continuously aware of new projects and their specifications</p>
    <p><a href="/search" class="btn btn-primary btn-large">Start Searching &raquo;</a></p>-->
	<div style="margin-top:18px">
	Due to a depressed economy, there's escalating competition for jobs in today’s public contract industry; so, it is vital to have an edge over competitors when seeking bids, RFPs, or Contracts.  JerseyBids provides that advantage.
	</div>
	<div style="margin-top:18px">
	JerseyBids supplies updates and knowledgeon current and upcoming bids, RFPs, and government contracts to keep you, the contractor, continuously aware of new projects and their specifications. We offer a database of New Jersey bids at no charge to you!
	</div>
	<div style="margin-top:18px">
	<i>Why JerseyBids?</i>  We remain ahead of the competition because we are the ONLY New Jersey specific site.  Gone are the frustrating days of wasting your time endlessly searching through information to locate contracting opportunities in your area.  Not only do we do the filtering work for you, but we offer this New Jersey focused service for free whereas you would pay a fee on any of other website.  
	</div>
	<div style="margin-top:18px">
	The State of New Jersey has 21 counties, 566 municipalities (250 boroughs, 52 cities, 15 towns, 245 townships, and 4 villages), 682 schools districts, 15 State departments, and 71 agencies.  Each of these entities list bids, contracts and RFPs.  As a result, bidding in New Jersey can be complicated, confusing and overwhelming.  <b>JerseyBids is here to help</b>.
	</div>
</div>

{% endblock %}

bidmanager/templates/bids/howto.html
{% extends 'base.html' %}

{% block content %}
    <h1>The New Jersey Bid Process</h1>
    <br/>
    <p>We supply updates and knowledge on current and upcoming bids, RFPs, and government contracts to keep you, the contractor, continuously aware of new projects and their specifications</p>

    <hr/>

      <div class="row-fluid">
        <div class="span4">
          <h2>Counties A to I</h2>
          <p>
          	<a href="">Atlantic</a>
          </p>
        </div>
        <div class="span4">
          <h2>Counties J to R</h2>
          <p>
          	<a href="">Atlantic</a>
          </p>
       </div>
        <div class="span4">
          <h2>Counties S to Z</h2>
          <p>
          	<a href="">Atlantic</a>
          </p>
        </div>
      </div>    
{% endblock %}

bidmanager/templates/bids/location.html
{% extends 'base.html' %}
{% block title %}{{location}} Bids{% endblock %}
{% block onready %}	
{% endblock %}
{% block content %}

<div class="row">
	<div class="span8 offset1">

		<h2>{{location}} Bids</h2>
		<table class="table table-striped table-bordered table-condensed">
			<thead>
			<tr>
				<th width="15%">County</th>
				<th width="15%">Category</th>
				<th width="60%">Title</th>
				<th width="10%">Date</th>
			</tr>
			</thead>
			<tbody>
			{% for r in bids %}
				{% include 'bids/_result.html' %}
			{% endfor %}
			</tbody>
		</table>

	</div>
</div>


{% endblock %}

bidmanager/templates/bids/search.html
{% extends 'base.html' %}
{% load endless %}

{% block title %}Search Bids{% endblock %}
{% block onready %}
	recheck_from_url();
	$('#query').pressEnter(function(){search();})

	$("tr.clickable").click(function() {
  		window.location.href = $(this).find("a").attr("href");
	});
	
{% endblock %}
{% block content %}
	<br/>

<div class="row">
	<div class="span2">
		<!--
		<div id="levels" class="facet">	
			<h3>Level</h3>
			<span class="divider"></span>
			{% for l in levels %}	
				<input onclick="search()" type="checkbox" name="level" id="level_{{l}}" value="{{l}}" />
				<label for="level_{{l}}">{{l|capfirst}}</label>
				<div style="clear:both; height:0px;"></div>
			{% endfor %}
		</div>		
		-->
		<br/>		
		<div id="counties" class="facet">	
			<h3>Counties</h3>
			<span class="divider"></span>
			<div style="height:150px; overflow:scroll; padding-left:2px;">
			{% for c in counties %}	
				<input onclick="search()" type="checkbox" name="county" id="county_{{c.0}}" value="{{c.0}}" />
				<label for="county_{{c.0}}">{{c.0|capfirst}}</label>
				<div style="clear:both; height:0px;"></div>
			{% endfor %}
			</div>
		</div>		
		<br/>
		<div id="categories" class="facet">		
			<h3>Categories</h3>
			<span class="divider"></span>
			{% for c in cats %}
				<input onclick="search()" type="checkbox" name="category" id="category_{{c.0}}" value="{{c.0}}" />
				<label for="county_{{c.0}}">{{c.0|capfirst}}</label>
				<div style="clear:both; height:0px;"></div>
			{% endfor %}
		</div>
		<br>
	</div>
	<div class="span10">
		<div class="row">
		<div class="span5">
			<div class="input-append">
				<input id="query" type="text">
				<button class="btn" type="button" onclick="search()">Search</button>
			</div>
		</div>
		<div class="span2">
			<select name="orderby" style="float:left" onchange="search()">
				<option>Order By</option>
				<option value="date">Newest</option>
				<option value="county">County</option>
				<option value="category">Category</option>
			</select>
		</div>
		</div>
		<br>
		<b>{{result_title}}</b><br>
		<table class="table table-striped table-bordered table-condensed">
			<thead>
			<tr>
				<th width="15%">County</th>
				<th width="15%">Category</th>
				<th width="60%">Title</th>
				<th width="10%">Date</th>
			</tr>
			</thead>
			<tbody>
			{% paginate results %}
			{% for r in results %}
				{% include 'bids/_search_result.html' %}
			{% endfor %}
			</tbody>
		</table>

		<div class="pagination">
		<ul>
			{% get_pages %}
			{% for page in pages %}
				<!--{% if page.number == 2 %}
				<li>{{ pages.previous }}</li>
				{% endif %}	-->		
				<li>{{page}}	</li>
			{% endfor %}
			<li>{{ pages.next }}</li>
		</ul>
		</div>
	</div>
</div>


{% endblock %}